name: 'Deploy App Engine'
description: 'This action allowed you publish application to Google App Engine'
inputs:
  service-account:
    description: 'Service account file'
    required: true
  project-id:
    description: 'Project id'
    required: true
  debug:
    description: 'Debug action'
    dafault: false
  path:
    description: 'app.yaml path'
    default: ./
  yaml:
    description: 'app.yaml name. Default app.yaml'
    default: app.yaml
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'box'
  color: 'blue'
